apiVersion: v1
kind: Service

metadata:
  name: {{ include "order-service.fullname" . }}

  labels:
{{ include "order-service.labels" . | indent 4 }}

spec:
  type: {{ .Values.service.type }}

  selector:
{{ include "order-service.selectorLabels" . | indent 4 }}

  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP